site_name: Sistemas Multiagentes

theme:
  name: material
 
  features:
    - toc.integrate
   
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para a preferência do sistema
  

nav:
  - Página Inicial: index.md
  - Módulo Investigando: modulo_investigando.md
  - Reuniões:
      - Módulo Investigando: reuniao_1.md
  - Participações: 
      - Módulo Investigando: participacao_m1.md

