site_name: Sistemas Multiagentes

theme:
  name: material
  
  features:
    - toc.integrate
  
extra_javascript:
  - js/toggle-theme.js
  

nav:
 - Página Inicial: index.md
 - Módulo Investigativo: modulo_investigativo.md