site_name: Sistemas Multiagentes

theme:
  name: material
 
  features:
    - toc.integrate
   
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para a preferência do sistema
  

nav:
  - Página Inicial: index.md
  - Módulo Investigando: 
      - Introdução: modulo_investigando.md
      - Reunião: reuniao_1.md
      - Participações: participacao_m1.md
  - Módulo Aplicando:
      - Introdução: modulo_aplicando.md
      - Reuniões:
          - 2024: reuniao_2.md
          - 2025: reuniao_3.md
      - Participações: participacao_m2.md
  - Módulo Publicando:
      - Introdução: modulo_publicando.md
      - Reunião: reuniao_4.md