name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Gatilho para o branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Altere para a versão do Python usada no projeto

    - name: Install MkDocs and Dependencies
      run: |
        pip install mkdocs mkdocs-material ghp-import

    - name: Build and Deploy
      run: |
        mkdocs gh-deploy --force
